name: Unit Tests

on:
  workflow_call:
    inputs:
      node_env:
        required: true
        type: string

concurrency:
  # Ensures that only one workflow task will run at a time. Previous builds, if
  # already in process, will get cancelled. Only the latest commit will be allowed
  # to run, cancelling any workflows in between
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NODE_ENV: ${{ inputs.node_env }}
  CI: true

permissions: read-all

jobs:
  test:
    name: Test with Node.js ${{ matrix.node }}
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [lts/*, latest]

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4.1.7

      - uses: pnpm/action-setup@v4.0.0

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      # - name: Audit for vulnerabilities
      #   run: npx audit-ci@^6 --config ./audit-ci.jsonc

      - name: Install and Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
